trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UseDotNet@2
  displayName: 'Use .NET 6'
  inputs:
    packageType: sdk
    version: 2.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet tool install -g Wyam.Tool
  displayName: 'Install Wyam'

- script: |
    pushd src
    export PATH=$PATH:$HOME/.dotnet/tools
    wyam build
    ln -s $(pwd)/output $(Build.ArtifactStagingDirectory)/output
    popd
  displayName: 'Generate the static site'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)/output
    artifactName: 'site'
    publishLocation: 'container'
  displayName: 'Publish site artifact'
