trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: dotnet tool install -g Wyam.Tool
  displayName: 'Install Wyam'

- script: |
    export PATH=$PATH:$HOME/.dotnet/tools
    pushd src
    wyam build
    popd
  displayName: 'Generate the static site'


